formatter: markdown table

output:
  file: README.md
  mode: inject

sort:
  enabled: true
  by: required

content: |-
  {{ .Header }}
  {{ .Resources }}
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Footer }}

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
